### ISSUE TITLE
挂了，修一下吧

### ISSUE THREAD

**Issue by reman-l** [BlueSkyXN/V2EX-Checkin#2]
## 开始执行... 2024-04-27 14:36:35

----------V2EX开始尝试签到----------
Traceback (most recent call last):
  File "/ql/data/scripts/v2ex.py", line 97, in <module>
    main()
  File "/ql/data/scripts/v2ex.py", line 88, in main
    msg += run(cookie)
           ^^^^^^^^^^^
  File "/ql/data/scripts/v2ex.py", line 54, in run
    sign_url = f"https://www.v2ex.com/mission/daily/redeem?{once[0]}"
                                                            ~~~~^^^
TypeError: 'NoneType' object is not subscriptable

## 执行结束... 2024-04-27 14:36:39  耗时 4 秒

**Comment by BlueSkyXN** [comment]
不怎么用了，应该是有CF盾
